image: oven/bun:1.4

cache: # Cache modules in between jobs
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .bun-cache/

variables:
  BUN_INSTALL_CACHE_DIR: $CI_PROJECT_DIR/.bun-cache

before_script:
  - bun install --frozen-lockfile

stages:
  - test-unit
  - test-e2e
  - test-server
  - lint
  - lint-css
  - build

# Only showing coverage for unit tests
unit-test-job:
  stage: test-unit
  script:
    - echo "Running unit tests..."
    - cd client
    - bun run coverage
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    when: always
    paths:
      - ./client/coverage/
    reports:
      junit: ./client/coverage/junit.xml

e2e-test-job:
  stage: test-e2e
  image: mcr.microsoft.com/playwright:v1.63.0-noble
  before_script:
    - npm install -g bun
    - bun install --frozen-lockfile
  script:
    - echo "Running e2e tests..."
    - cd client
    - bun run test:e2e:ci

server-test-job:
  stage: test-server
  script:
    - echo "Running unit tests..."
    - cd server
    - bun run test

lint-test-job 1/2:
  stage: lint
  script:
    - echo "Linting code..."
    - bun run lint
    - echo "No lint issues found."

lint-test-job 2/2:
  stage: lint-css
  script:
    - echo "Linting code..."
    - bun run lint:style
    - echo "No lint issues found."

build-client:
  stage: build
  script:
    - echo "Compiling the code..."
    - cd client
    - bun run build
    - echo "Compile complete."
